Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -70,31 +70,31 @@ jobs:
           echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
           echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV
 
-      # - name: Run mlflow project and Get latest MLflow run_id
-      #   id: get_run_id # Mengubah ID agar lebih deskriptif
-      #   run: |
-      #     cd MLproject
-      #     mlflow run . -P data_path=clothes_preprocessing.csv --env-manager=local | tee output.log
-      #     RUN_ID=$(grep 'MLFLOW_RUN_ID=' output.log | cut -d'=' -f2)
-
-      #     echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
-      #     echo "Latest MLflow Run ID: $RUN_ID"
-
       - name: Run mlflow project and Get latest MLflow run_id
         id: get_run_id # Mengubah ID agar lebih deskriptif
         run: |
           cd MLproject
-          # Menangkap output dari mlflow run secara langsung
-          MLFLOW_RUN_COMMAND_OUTPUT=$(mlflow run . -P data_path=clothes_preprocessing.csv --env-manager=local)
-          echo "$MLFLOW_RUN_COMMAND_OUTPUT" | tee output.log # Tetap simpan ke file jika perlu debugging
-          # Ekstrak RUN_ID dari output (MLflow akan mencetaknya jika berhasil)
-          RUN_ID=$(echo "$MLFLOW_RUN_COMMAND_OUTPUT" | grep 'MLFLOW_RUN_ID=' | cut -d'=' -f2 | tr -d '\r') # tr -d '\r' untuk menghapus carriage return jika ada
-          if [ -z "$RUN_ID" ]; then
-            echo "Error: MLFLOW_RUN_ID not found in output.log. Check MLflow execution."
-            exit 1
-          fi
+          mlflow run . -P data_path=clothes_preprocessing.csv --env-manager=local | tee output.log
+          RUN_ID=$(grep 'MLFLOW_RUN_ID=' output.log | cut -d'=' -f2)
+
           echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
           echo "Latest MLflow Run ID: $RUN_ID"
+
+      # - name: Run mlflow project and Get latest MLflow run_id
+      #   id: get_run_id # Mengubah ID agar lebih deskriptif
+      #   run: |
+      #     cd MLproject
+      #     # Menangkap output dari mlflow run secara langsung
+      #     MLFLOW_RUN_COMMAND_OUTPUT=$(mlflow run . -P data_path=clothes_preprocessing.csv --env-manager=local)
+      #     echo "$MLFLOW_RUN_COMMAND_OUTPUT" | tee output.log # Tetap simpan ke file jika perlu debugging
+      #     # Ekstrak RUN_ID dari output (MLflow akan mencetaknya jika berhasil)
+      #     RUN_ID=$(echo "$MLFLOW_RUN_COMMAND_OUTPUT" | grep 'MLFLOW_RUN_ID=' | cut -d'=' -f2 | tr -d '\r') # tr -d '\r' untuk menghapus carriage return jika ada
+      #     if [ -z "$RUN_ID" ]; then
+      #       echo "Error: MLFLOW_RUN_ID not found in output.log. Check MLflow execution."
+      #       exit 1
+      #     fi
+      #     echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
+      #     echo "Latest MLflow Run ID: $RUN_ID"
 
       - name: Commit and push processed files
         env:
